/**
 * A class representing `HmacAuthenticationDefaults`.
 */
export class HmacAuthenticationDefaults {
    /**
     * The name of the hmac `AuthenticationScheme`. This is the scheme
     * used as the authorization header for requests signed with `IHmacManager`.
     */
    static readonly AuthenticationScheme = "Hmac";

    /**
     * The name of the `DefaultPolicy`. This is always set to "Default".
     */
    static readonly DefaultPolicy = "Default";

    /**
     * A class representing `Headers`. These are the minimum required
     * headers that are automatically added to requests signed with an `IHmacManager` implementation.
     */
    static Headers = class {
        /** 
         * Represents the standard HTTP `Authorization` header key used for passing authentication credentials.
         */
        static readonly Authorization = "Authorization";

        /**
         * The `Policy` header value. Identifies the policy to sign and verify requests.
         * This is configured through an instance of `HmacManagerOptions`.
         */
        static readonly Policy = `${HmacAuthenticationDefaults.AuthenticationScheme}-Policy`;

        /**
         * The `Scheme` header value. Identifies the `Scheme` to sign and verify requests with. 
         * This is configured through an instance of `HmacManagerOptions`.
         */
        static readonly Scheme = `${HmacAuthenticationDefaults.AuthenticationScheme}-Scheme`;

        /**
         * The `Nonce` header value. This is automatically generated by
         * `IHmacManager` when signing and verifying requests.
         */
        static readonly Nonce = `${HmacAuthenticationDefaults.AuthenticationScheme}-Nonce`;
        
        /**
         * The `DateRequested` header value. This is automatically generated by
         * `IHmacManager` when signing and verifying requests.
         */
        static readonly DateRequested = `${HmacAuthenticationDefaults.AuthenticationScheme}-DateRequested`;
    }
}