version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/client/lib"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/client/sample"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/samples/WebToApiAuthenticationWithJavaScriptClient/Web/src"
    schedule:
      interval: "weekly"
