apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hmac-manager.fullname" . }}-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hmac-manager.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
