{{- if and .Values.redis.enabled .Values.redis.bundled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hmac-manager.fullname" . }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hmac-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hmac-manager.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: redis
  template:
    metadata:
      labels:
        {{- include "hmac-manager.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          args:
            - --save
            - ""
            - --appendonly
            - "no"
{{- end }}
