{{- if and .Values.redis.enabled .Values.redis.bundled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hmac-manager.fullname" . }}-redis
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hmac-manager.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "hmac-manager.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
