apiVersion: v1
kind: Service
metadata:
  name: {{ include "hmac-manager.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hmac-manager.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "hmac-manager.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
