version: 0.1.0
name: hmac-manager
displayName: HMAC Manager
createdAt: "2026-06-30T00:00:00Z"
description: Istio ext-authz HTTP server for HMAC request authentication
logoURL: ""
digest: ""
license: MIT
homeURL: https://github.com/jzills/hmac-manager
keywords:
  - hmac
  - authentication
  - istio
  - ext-authz
  - security
links:
  - name: Source
    url: https://github.com/jzills/hmac-manager
  - name: NuGet
    url: https://www.nuget.org/packages/HmacManager
maintainers:
  - name: Joshua Zillwood
    email: joshua.zillwood@gmail.com
provider:
  name: Joshua Zillwood
recommendations: []
