export namespace HmacAuthenticationDefaults {
    /**
     * The name of the hmac `AuthenticationScheme`. This is the scheme
     * used as the authorization header for requests signed with `IHmacManager`.
     */
    export const AuthenticationScheme = "Hmac";

    /**
     * An enum representing `Headers`. These are the minimum required
     * headers that are automatically added to requests signed with an `IHmacManager` implementation.
     */
    export enum Headers {
        /** 
         * Represents the standard HTTP `Authorization` header key used for passing authentication credentials.
         */
        Authorization = "Authorization",

        /**
         * The `Policy` header value. Identifies the policy to sign and verify requests.
         * This is configured through an instance of `HmacManagerOptions`.
         */
        Policy = `${AuthenticationScheme}-Policy`,

        /**
         * The `Scheme` header value. Identifies the `Scheme` to sign and verify requests with. 
         * This is configured through an instance of `HmacManagerOptions`.
         */
        Scheme = `${AuthenticationScheme}-Scheme`,

        /**
         * The `Nonce` header value. This is automatically generated by
         * `IHmacManager` when signing and verifying requests.
         */
        Nonce = `${AuthenticationScheme}-Nonce`,
        
        /**
         * The `DateRequested` header value. This is automatically generated by
         * `IHmacManager` when signing and verifying requests.
         */
        DateRequested = `${AuthenticationScheme}-DateRequested`,

        /**
         * The `Options` header value. This is automatically generated by
         * `IHmacManager` when signing and verifying requests.
         */
        Options = `${AuthenticationScheme}-Options`
    }
}