namespace HmacManager.Mvc;

/// <summary>
/// A class representing <c>HmacAuthenticationDefaults</c>.
/// </summary>
public static class HmacAuthenticationDefaults
{
    /// <summary>
    /// The name of the hmac <c>AuthenticationScheme</c>. This is the scheme
    /// used as the authorization header for requests signed with <c>IHmacManager</c>.
    /// </summary>
    public const string AuthenticationScheme = "Hmac";

    /// <summary>
    /// The name of the <c>DefaultPolicy</c>. This is always set to "Default".
    /// </summary>
    public const string DefaultPolicy = "Default";

    /// <summary>
    /// A class representing <c>Headers</c>. These are the minimum required
    /// headers that are automatically added to requests signed with an <c>IHmacManager</c> implementation.
    /// </summary>
    public class Headers
    {
        /// <summary>
        /// The <c>Policy</c> header value. Identifies the policy to sign and verify requests.
        /// This is configured through an instance of <c>HmacManagerOptions</c>.
        /// </summary>
        public const string Policy = "X-Hmac-Policy";

        /// <summary>
        /// The <c>Scheme</c> header value. Identifies the <c>Scheme</c> to sign and verify requests with. 
        /// This is configured through an instance of <c>HmacManagerOptions</c>.
        /// </summary>
        public const string Scheme = "X-Hmac-Scheme";

        /// <summary>
        /// The <c>Nonce</c> header value. This is automatically generated by
        /// <c>IHmacManager</c> when signing and verifying requests.
        /// </summary>
        public const string Nonce = "X-Hmac-Nonce";
        
        /// <summary>
        /// The <c>DateRequested</c> header value. This is automatically generated by
        /// <c>IHmacManager</c> when signing and verifying requests.
        /// </summary>
        public const string DateRequested = "X-Hmac-Date-Requested";
    }

    internal class Properties
    {
        internal const string PolicyProperty = $"{nameof(HmacManager)}.Policy";
        internal const string SchemeProperty = $"{nameof(HmacManager)}.Scheme";
    }
}