namespace HmacManager.Mvc;

/// <summary>
/// A class representing <see cref="HmacAuthenticationDefaults"/>.
/// </summary>
public static class HmacAuthenticationDefaults
{
    /// <summary>
    /// The name of the hmac <see cref="AuthenticationScheme"/>. This is the scheme
    /// used as the authorization header for requests signed with <see cref="IHmacManager"/>.
    /// </summary>
    public const string AuthenticationScheme = "Hmac";

    /// <summary>
    /// A class representing <see cref="Headers"/>. These are the minimum required
    /// headers that are automatically added to requests signed with an <see cref="IHmacManager"/> implementation.
    /// </summary>
    public class Headers
    {
        /// <summary>
        /// The standard authorization header.
        /// </summary>
        public const string Authorization = nameof(Authorization);

        /// <summary>
        /// The <see cref="Policy"/> header value. Identifies the policy to sign and verify requests.
        /// This is configured through an instance of <see cref="HmacManagerOptions"/>.
        /// </summary>
        public const string Policy = $"{AuthenticationScheme}-{nameof(Policy)}";

        /// <summary>
        /// The <see cref="Scheme"/> header value. Identifies the <see cref="Scheme"/> to sign and verify requests with. 
        /// This is configured through an instance of <see cref="HmacManagerOptions"/>.
        /// </summary>
        public const string Scheme = $"{AuthenticationScheme}-{nameof(Scheme)}";

        /// <summary>
        /// The <see cref="Nonce"/> header value. This is automatically generated by
        /// <see cref="IHmacManager"/> when signing and verifying requests.
        /// </summary>
        public const string Nonce = $"{AuthenticationScheme}-{nameof(Nonce)}";
        
        /// <summary>
        /// The <see cref="DateRequested"/> header value. This is automatically generated by
        /// <see cref="IHmacManager"/> when signing and verifying requests.
        /// </summary>
        public const string DateRequested = $"{AuthenticationScheme}-{nameof(DateRequested)}";

        /// <summary>
        /// The <see cref="Options"/> header value. This is automatically generated by
        /// <see cref="IHmacManager"/> when signing and verifying requests.
        /// </summary>
        public const string Options = $"{AuthenticationScheme}-{nameof(Options)}";
    }

    /// <summary>
    /// A class that defines constants representing property names for HMAC-related data in authentication properties.
    /// These constants are used to store and retrieve the HMAC policy and scheme values.
    /// </summary>
    internal class Properties
    {
        /// <summary>
        /// The constant representing the key for the HMAC policy in authentication properties.
        /// </summary>
        internal const string PolicyProperty = $"{nameof(HmacManager)}.Policy";
        
        /// <summary>
        /// The constant representing the key for the HMAC scheme in authentication properties.
        /// </summary>
        internal const string SchemeProperty = $"{nameof(HmacManager)}.Scheme";
    }
}