namespace HmacManager.Mvc;

/// <summary>
/// A class representing <c>HmacAuthenticationDefaults</c>.
/// </summary>
public static class HmacAuthenticationDefaults
{
    /// <summary>
    /// The name of the hmac <c>AuthenticationScheme</c>. This is the scheme
    /// used as the authorization header for requests signed with <c>IHmacManager</c>.
    /// </summary>
    public const string AuthenticationScheme = "Hmac";

    /// <summary>
    /// A class representing <c>Headers</c>. These are the minimum required
    /// headers that are automatically added to requests signed with an <c>IHmacManager</c> implementation.
    /// </summary>
    public class Headers
    {
        /// <summary>
        /// The standard authorization header.
        /// </summary>
        public const string Authorization = nameof(Authorization);

        /// <summary>
        /// The <c>Policy</c> header value. Identifies the policy to sign and verify requests.
        /// This is configured through an instance of <c>HmacManagerOptions</c>.
        /// </summary>
        public const string Policy = $"{AuthenticationScheme}-{nameof(Policy)}";

        /// <summary>
        /// The <c>Scheme</c> header value. Identifies the <c>Scheme</c> to sign and verify requests with. 
        /// This is configured through an instance of <c>HmacManagerOptions</c>.
        /// </summary>
        public const string Scheme = $"{AuthenticationScheme}-{nameof(Scheme)}";

        /// <summary>
        /// The <c>Nonce</c> header value. This is automatically generated by
        /// <c>IHmacManager</c> when signing and verifying requests.
        /// </summary>
        public const string Nonce = $"{AuthenticationScheme}-{nameof(Nonce)}";
        
        /// <summary>
        /// The <c>DateRequested</c> header value. This is automatically generated by
        /// <c>IHmacManager</c> when signing and verifying requests.
        /// </summary>
        public const string DateRequested = $"{AuthenticationScheme}-{nameof(DateRequested)}";

        /// <summary>
        /// The <c>Options</c> header value. This is automatically generated by
        /// <c>IHmacManager</c> when signing and verifying requests.
        /// </summary>
        public const string Options = $"{AuthenticationScheme}-{nameof(Options)}";
    }

    /// <summary>
    /// A class that defines constants representing property names for HMAC-related data in authentication properties.
    /// These constants are used to store and retrieve the HMAC policy and scheme values.
    /// </summary>
    internal class Properties
    {
        /// <summary>
        /// The constant representing the key for the HMAC policy in authentication properties.
        /// </summary>
        internal const string PolicyProperty = $"{nameof(HmacManager)}.Policy";
        
        /// <summary>
        /// The constant representing the key for the HMAC scheme in authentication properties.
        /// </summary>
        internal const string SchemeProperty = $"{nameof(HmacManager)}.Scheme";
    }
}