name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup redis
      uses: supercharge/redis-github-action@1.2.0
      with: 
          redis-version: 6
    - name: Install redis cli 
      run: sudo apt-get install -y redis-tools
    - name: Verify that redis is up
      run: redis-cli ping
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      working-directory: ./test/Unit
      run: dotnet restore
    - name: Build
      working-directory: ./test/Unit
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./test/Unit
      run: dotnet test --no-build --verbosity normal
